---
- name: Install java and net-tools
  hosts: 64.226.95.172
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      ansible.builtin.apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      ansible.builtin.apt: name=net-tools  

- name: Download and unpack Nexus installer
  hosts: 64.226.95.172
  tasks: 
    - name: Download Nexus
      ansible.builtin.get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      ansible.builtin.unarchive:
        # Name of the downloaded file on the server which is located at /opt/
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
    - name: Find nexus folder
      ansible.builtin.find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: Check nexus folder stats
      ansible.builtin.stat:
        path: /opt/nexus
      register: stat_result
      # rename the folder to nexus
    - name: Rename nexus folder
      # We can print the find_result again to see how to access the value we want here.
      ansible.builtin.shell: mv {{find_result.files[0].path}} /opt/nexus
      # Avoid re-execution of above shell command if the nexus folder already exists
      when: not stat_result.stat.exists

- name: Create nexus user to own nexus folders
  hosts: 64.226.95.172
  tasks:
    - name: Ensure group nexus exists
      ansible.builtin.group:
        name: nexus
        state: present
    - name: Create nexus user
      ansible.builtin.user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      ansible.builtin.file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      ansible.builtin.file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
